import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Header from "@/components/header/header"
import Footer from "@/components/footer/footer"
import "./globals.css";
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
      <Toaster/>
          <Header />
            <main className="flex-grow p-4 md:p-6">
              {children}
            </main>
              <Footer />
      </body>
    </html>
  );
}
